# Configure here which dependency updates should be merged automatically.
# Format: https://github.com/iobroker-bot-orga/action-automerge-dependabot#auto-merge-configuration-file
# Matching is hierarchical: "semver:minor" includes patch updates.
- match:
      # Only merge patches for production dependencies
      dependency_type: production
      update_type: "semver:patch"
- match:
      # development dependencies can have a minor update, too
      dependency_type: development
      update_type: "semver:minor"
- match:
      # lockfile-only changes (transitive dependencies)
      dependency_type: package-lock
      update_type: "semver:minor"
